### ISSUE TITLE
Icon hard to see

### ISSUE THREAD

**Issue by v0l** [CodyTseng/nostr-relay-tray#19]
On Ubuntu dark theme you cannot see the icon unless you hover over

![image](https://github.com/CodyTseng/nostr-relay-tray/assets/1172179/eae730e9-e977-4239-aa56-3218cf2573fd)

**Comment by CodyTseng** [comment]
Hi @v0l ! Could you please try this PR #21  to see if it resolves your issue?

**Comment by CodyTseng** [comment]
<img width="74" alt="image" src="https://github.com/CodyTseng/nostr-relay-tray/assets/64680921/5a6f979f-209f-4efa-9eeb-3600565a3b8e">
<img width="79" alt="image" src="https://github.com/CodyTseng/nostr-relay-tray/assets/64680921/adafba3f-9471-46a7-a3bc-ca05688fb182">
The default color is now purple on the Linux and Windows platform, and it supports changing the color in the settings.
