### ISSUE TITLE
Payload too large

### ISSUE THREAD

**Issue by v0l** [CodyTseng/nostr-relay-tray#20]
Sending large follow lists seems to break the relay

![image](https://github.com/CodyTseng/nostr-relay-tray/assets/1172179/2c4746bc-ddf0-4dfc-a469-cd29d5b8ecd4)

**Comment by CodyTseng** [comment]
Related issue: https://github.com/CodyTseng/nostr-relay-tray/issues/8

Yeah, it currently does not accept events larger than 128k. This issue will be resolved soon.
