### ISSUE TITLE
No icon in the system tray

### ISSUE THREAD

**Issue by pomazanbohdan** [CodyTseng/nostr-relay-tray#30]
![image](https://github.com/user-attachments/assets/003a1093-48ff-40c4-9440-30cea6537488)

![image](https://github.com/user-attachments/assets/74f08a4b-eb95-4409-95d1-2b9583904572)

![image](https://github.com/user-attachments/assets/16196bd0-f317-4fe2-8bc8-542672d99e10)

**Comment by CodyTseng** [comment]
I'm not sure what the issue is at the moment, but I tried installing version 1.4.0 and then installing version 1.5.0, and the problem was resolved.

**Comment by CodyTseng** [comment]
fixed in https://github.com/CodyTseng/nostr-relay-tray/releases/tag/v1.5.1
